// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njjkzzqpyosutzanowyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qamt6enFweW9zdXR6YW5vd3l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2NTc4NzYsImV4cCI6MjA3NTIzMzg3Nn0.2QQ9zXEIsCxRkcmts4uy1pAmbnC0UTJgQ0Qfjs_1CCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});