// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmfssdcjyzynskmvogzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZnNzZGNqeXp5bnNrbXZvZ3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjEzMzcsImV4cCI6MjA3NDM5NzMzN30._YWx7W0NxrEOF1Mb55gOzGOtJftrs1Bit0v7gZRiml8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});